---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность сбрасывать применённые фильтры и возвращаться к исходному списку товаров
  - Пользователь должен иметь возможность удалять товары из корзины
  - Состояние корзины должно сохраняться при закрытии браузера или при переходах между страницами
  - На странице товара должно быть название товара
  - На странице товара должен быть указан рейтинг товара
  - На странице товара должна отображаться цена товара без скидки
  - На странице товара должна отображаться цена товара со скидкой
  - После оформления заказа должна появляться страница оплаты
  - Сайт должен иметь механизмы кеширования для снижения нагрузки
