---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - В поле поиска можно вводить только буквенные значения
  - Пользователь должен иметь возможность сбрасывать применённые фильтры и возвращаться к исходному списку товаров
  - Пользователь должен иметь возможность удалять товары из корзины
  - Пользователь должен иметь возможность выбирать количество товаров при добавлении их в корзину
  - Корзина должна сохранять состояние при уходе пользователя с сайта
  - Сайт должен соответствовать стандартам доступности для людей с ограниченными возможностями
  - Все данные, передаваемые между клиентом и сервером, должны быть зашифрованы с использованием HTTPS
  - Сайт должен защищать данные пользователя в соответствии с Федеральным законом РФ "О персональных данных" №152
  - Сайт должен поддерживаться на мобильных устройствах и быть адаптивным
  - Сайт должен поддерживаться на различных операционных системах
  - Сайт должен должен обрабатывать минимум 500 заказов в час
  - Сайт должен иметь механизмы кеширования для снижения нагрузки
